name: Unit Test

on:
  push:
    branches: [ main ]  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test  -p:CollectCoverage=true -p:CoverletOutput=TestResults/ -p:CoverletOutputFormat=opencover --no-build --verbosity normal
    - name: Create Test Coverage Badge
      uses: simon-k/dotnet-code-coverage-badge@v1.0.0
      id: create_coverage_badge
      with:
        label: Code Coverage
        color: brightgreen
        path: tests/TryCatch.MongoDb.UnitTests/TestResults/coverage.opencover.xml
        gist-filename: trycatch.mongodb-code-coverage.json
        gist-id: d329d88d2223613ccf3f9ec704d707b5
        gist-auth-token: ${{ secrets.GIST_CQRS_BADGE }}       
    - name: Print code coverage
      run: echo "Code coverage percentage ${{steps.create_coverage_badge.outputs.percentage}}%"      
